### ISSUE TITLE
Educational purposes

### ISSUE THREAD

**Issue by wrapper** [dmitry-kostin/termin-buchen#13]
Hey, thanks so much for making this script.

I get an error on line 26 of config.js because I tried to use educational purposes as the reason. Is there any reason why these categories are not included in the script?

Thanks

**Comment by mpendharkar** [comment]
I'm interested in this as well, please. Thank you! :)

**Comment by dmitry-kostin** [comment]
I believe this scenario hasn't been accounted for yet, and it seems you're the first how request for it. If you could take a screenshot and upload it here, I can include this use case since it's fairly straightforward to do so. Thank you!

**Comment by dmitry-kostin** [comment]
Meanwhile I've just added `educational` reason with following list of purposes:

```js
{
  edu_16f_1: 'Residence permit for attending a language course (sect. 16f para. 1)',
  edu_16a: 'Residence permit for in-service training (sect. 16a)',
  edu_16b_1: 'Residence permit for study preparation (sect. 16b para. 1)',
  edu_16b: 'Residence permit for the purpose of studying (sect. 16b)',
  edu_16d_1: 'Residence permit for the recognition of a foreign professional qualification in a non-regulated profession (sect. 16d para. 1)',
  edu_16d_3: 'Residence permit for the recognition of a foreign professional qualification in a non-regulated profession (§ 16d para. 3)',
  edu_16a_vocational: 'Residence permit for vocational training (sect. 16a)',
  edu_19c_1: 'Residence permit to start a traineeship (sect. 19c para. 1)',
  edu_16f: 'Residence permit to take part in a student exchange or to attend school (sect. 16f)'
}
```


example of usage as below, let me know if that's what you're looking for

```
REASON=educational
PURPOSE=edu_16b
```

**Comment by wrapper** [comment]
This is perfect! Running and working as expected thanks @dmitry-kostin 
cc @mpendharkar give it a go

**Comment by mpendharkar** [comment]
Thank you!! :)
