### ISSUE TITLE
Residence permit for scientific staff and research workers" 18d

### ISSUE THREAD

**Issue by Edouardbabo** [dmitry-kostin/termin-buchen#16]
hello thank you very much for helping us.
could you please add the section "Residence permit for scientific staff and research workers" 18d please.
I really need your help to renew my visa.

**Comment by dmitry-kostin** [comment]
Hey, sorry I am little busy this week, bit no worries I will be able to add this use case starting next week

**Comment by dmitry-kostin** [comment]
Hello,

Sorry for a delay, but I am finally happy to tell you that I have just included a variety of new use-cases, one of which is specifically tailored to your request.

For your convenience, I have provided an example configuration that aligns with your case (sect. 18d) below.

To access these latest changes, please make sure you execute git pull to fetch the most recent changes from repository.
In the event that you encounter any errors, particularly those related to the unknown config values, I recommend removing `build` folder before proceeding.

```
MAIN_CITIZENSHIP=Russian Federation
NUMBER_OF_PEOPLE=one person
LIVE_WITH=yes
PARTNER_CITIZENSHIP=Germany
CATEGORY=apply
REASON=economic
PURPOSE=18d
```

**Comment by Edouardbabo** [comment]
> Hello,
> 
> Sorry for a delay, but I am finally happy to tell you that I have just included a variety of new use-cases, one of which is specifically tailored to your request.
> 
> For your convenience, I have provided an example configuration that aligns with your case (sect. 18d) below.
> 
> To access these latest changes, please make sure you execute git pull to fetch the most recent changes from repository. In the event that you encounter any errors, particularly those related to the unknown config values, I recommend removing `build` folder before proceeding.
> 
> ```
> MAIN_CITIZENSHIP=Russian Federation
> NUMBER_OF_PEOPLE=one person
> LIVE_WITH=yes
> PARTNER_CITIZENSHIP=Germany
> CATEGORY=apply
> REASON=economic
> PURPOSE=18d
> ```

thank you very much . God bless you
