### ISSUE TITLE
Adding Residence permit for qualified skilled workers with an academic education

### ISSUE THREAD

**Issue by olgazhartun** [dmitry-kostin/termin-buchen#17]
Hey Dmitry!
Could you please add the purpose "Residence permit for qualified skilled workers with an academic education (sect. 18b)" and shortly explain what adjustments you made, I did my best to change it myself, adding the purpose to different files including config.js and second-page-scenario.ts, but still got an Error: PURPOSE config value is unknown, probably I'm missing something. Just too curious what is needed to do :)

I'm desperately trying to book a termin and would be more than happy about any help!

Спасибо большое за скрипт, надеюсь, что он сработает :)

**Comment by dmitry-kostin** [comment]
Dear Olga,

I am happy to tell you that I have recently included a variety of new use-cases, one of which is specifically tailored to your request.

For your convenience, I have provided an example configuration that aligns with your case (sect. 18b) below. 


To access these latest changes, please make sure you execute `git pull` to fetch the most recent changes from repository.
In the event that you encounter any errors, particularly those related to the unknown config values, I recommend removing `build` folder before proceeding. 


```
MAIN_CITIZENSHIP=Russian Federation
NUMBER_OF_PEOPLE=one person
LIVE_WITH=yes
PARTNER_CITIZENSHIP=Germany
CATEGORY=apply
REASON=economic
PURPOSE=18b
```

Удачи в поиске термина!

**Comment by olgazhartun** [comment]
Dmitry thanks a million for responding and adding new cases so quickly. I tried it out and it works!
Your script is so much help, thank you once again!
