### ISSUE TITLE
setCitizenship does not fill citizenship

### ISSUE THREAD

**Issue by apdullahyayik** [dmitry-kostin/termin-buchen#8]
`setCitizenship` does not fill citizenship in the UI, and this leads throwing the following error, and `result` becomes `true`

```
[runner]: started iteration 94
[findSlot]: error TimeoutError: Waiting for element to be located By(xpath, //*[@id="messagesBox"]/ul/li)
Wait timed out after 200007ms
[runner]: iteration 94 result: true
```
NPM version: 20

**Comment by dmitry-kostin** [comment]
ya, thanks for the feedback, that might happen from time to time when the portal becomes unresponsive.
meanwhile I guess that's not a common error, so simple restart probably would help. 
> There are can be a lot of false positives, that's why you need to keep an eye on console to check why execution stopped and restart again if needed.

**Comment by apdullahyayik** [comment]
@dmitry-kostin Thank you 👏 

I made what you suggested in this way:

I have initiated your codes with 10 different threads using Python in 3 different PCs 😄 some of them created the error 🐛 explained in this PR, but one of them achieved to catch a slot  🎯 , Wow I am shocked 🤗 

**Note 1**
I have also set this at src/const/timeout.ts;

```JS
export const CHECK_INTERVAL = 5 * 1000; 
```
**Note 2**
I have started running code after 07:20 in the morning ⏰ ,it took 30 min to catch on my end.

**Comment by dmitry-kostin** [comment]
Thanks, I appreciate your feedback!
and I'm genuinely pleased that it helped you to find a slot. 👍🏻
